#! /bin/bash

# stop script when an error occurs
set -e

psql -q -c "CREATE USER nsmm SUPERUSER PASSWORD '123'"
echo "Created Postgres user 'nsmm'"

psql -q -c "CREATE DATABASE chummyDB WITH OWNER nsmm"
echo "Created Postgres database 'chummyDB'"

cp -r example.env .env
echo "Created .env containing DATABASE_URL"